default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: tracker_development

test:
  <<: *default
  database: tracker_test

production:
  primary:
    adapter: mysql2
    encoding: utf8mb4
    reconnect: false
    database: tracker_production
    pool: 5
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: localhost
    port: 3306

  cable:
    adapter: mysql2
    encoding: utf8mb4
    database: tracker_cable
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: localhost

  queue:
    adapter: mysql2
    encoding: utf8mb4
    database: tracker_queue
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: localhost
